# Generated by Django 5.2 on 2025-07-06 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatgroup_group_name"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="group_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="chat.chatgroup",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
