# Generated by Django 5.2 on 2025-08-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_rename_is_active_workflowtemplate_is_published_and_more"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="workflow",
        ),
        migrations.AddField(
            model_name="task",
            name="workflow_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="automation.workflowinstance",
            ),
        ),
        migrations.AlterField(
            model_name="taskdependency",
            name="from_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_task",
                to="leads.task",
            ),
        ),
        migrations.AlterField(
            model_name="taskdependency",
            name="to_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_task",
                to="leads.task",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
