# Generated by Django 5.2 on 2025-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_remove_task_workflow_task_workflow_instance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
