# Generated by Django 5.2 on 2025-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_task_group_chat_alter_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
