# Generated by Django 5.2 on 2025-07-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_company_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdocuments",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="task_documents/"),
        ),
        migrations.AlterField(
            model_name="taskdocuments",
            name="file_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
