# Generated by Django 5.2 on 2025-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
