# Generated by Django 5.2 on 2025-07-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_task_completed_at_task_requires_approval_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='leads.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('suspended', 'Suspended'), ('completed', 'Completed'), ('pending', 'Pending'), ('pending_approval', 'Pending_approval')], max_length=20, null=True),
        ),
    ]
