# Generated by Django 5.2 on 2025-07-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_task_created_by_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('suspended', 'Suspended'), ('pending', 'Pending'), ('completed', 'Completed'), ('pending_approval', 'Pending_approval')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.CharField(choices=[('start_to_finish', 'Start to start'), ('start_to_start', 'Start to start'), ('finish_to_finish', 'Finish to finish'), ('finish_to_start', 'Finish to start')], max_length=40)),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='leads.task')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_tasks', to='leads.task')),
            ],
        ),
    ]
