# Generated by Django 5.2 on 2025-07-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_task_status_taskdependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                    ("pending_approval", "Pending_approval"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
