# Generated by Django 5.2 on 2025-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.AddField(
            model_name="task",
            name="create_group_chat",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
