# Generated by Django 5.2 on 2025-08-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatgroup_group_name"),
        ("leads", "0010_remove_task_category_task_create_group_chat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="group_chat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="chat.chatgroup",
            ),
        ),
    ]
