# Generated by Django 5.2 on 2025-08-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0004_templatetask_duration_alter_templatetask_description_and_more",
        ),
        ("leads", "0011_alter_task_group_chat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdependency",
            old_name="dependency",
            new_name="dependency_type",
        ),
        migrations.RemoveField(
            model_name="task",
            name="group_chat",
        ),
        migrations.AddField(
            model_name="task",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_tasks",
                to="automation.workflowtemplate",
            ),
        ),
        migrations.AddField(
            model_name="taskdependency",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.company",
            ),
            preserve_default=False,
        ),
    ]
