# Generated by Django 5.2 on 2025-07-06 20:18

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_chatgroup_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, unique=True),
        ),
    ]
