# Generated by Django 5.2 on 2025-07-10 15:53

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chatgroup_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(default=chat.models.generate_uuid, unique=True),
        ),
    ]
