# Generated by Django 5.2 on 2025-08-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatgroup_group_name"),
        ("leads", "0012_rename_dependency_taskdependency_dependency_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_chat",
                to="leads.task",
            ),
        ),
    ]
