# Generated by Django 5.2 on 2025-08-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatgroup_task"),
        ("leads", "0012_rename_dependency_taskdependency_dependency_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_chat",
                to="leads.task",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
