# Generated by Django 5.2 on 2025-07-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0009_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("pending_approval", "Pending_approval"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                (
                    "assignee",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional: employees to assign this task to by default",
                        to="leads.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("finish_to_start", "Finish to Start"),
                            ("start_to_start", "Start to Start"),
                            ("finish_to_finish", "Finish to Finish"),
                            ("start_to_finish", "Start to Finish"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "from_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_successors",
                        to="automation.templatetask",
                    ),
                ),
                (
                    "to_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_predecessors",
                        to="automation.templatetask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkFlowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leads.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="templatetask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_tasks",
                to="automation.workflowtemplate",
            ),
        ),
    ]
