# Generated by Django 5.2 on 2025-08-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetask",
            name="assignee",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: employees to assign this task to by default",
                to="leads.employee",
            ),
        ),
        migrations.AddField(
            model_name="templatedependency",
            name="from_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_successors",
                to="automation.templatetask",
            ),
        ),
        migrations.AddField(
            model_name="templatedependency",
            name="to_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_predecessors",
                to="automation.templatetask",
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leads.company"
            ),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leads.employee",
            ),
        ),
        migrations.AddField(
            model_name="templatetask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_tasks",
                to="automation.workflowtemplate",
            ),
        ),
    ]
