# Generated by Django 5.2 on 2025-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_workflowtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetask",
            name="chat_group",
            field=models.BooleanField(default=False),
        ),
    ]
