# Generated by Django 5.2 on 2025-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_templatetask_chat_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetask",
            name="duration",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="templatetask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templatetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=40,
            ),
        ),
    ]
